name: Build and deploy Storybook to Azure Web App

on:
  push:
    branches:
      - latest
      - master
  pull_request:
    branches:
      - latest
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: true
      - name: Pull submodule
        run: |
          git submodule update --remote --recursive
          cd test_images
          git checkout master
          cd ..
      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: yarn install
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: run linters
        run: |
          yarn lint:css
          yarn lint:package
          yarn lint:js
          yarn prettier-check

      - name: build library
        run: yarn build

      - name: typecheck storybook
        run: yarn typecheck:storybook

      - name: build storybook
        run: yarn build-storybook

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          record: false
          command: yarn run test
        env:
          CHOKIDAR_USEPOLLING: true
          CYPRESS_CICD: true 

      - name: Upload test snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
        run: |
          cd test_images
          git add .
          if git status | grep -q 'new file'
          then
            git commit -m "build(tests): Added test images"
            git push https://gitlab-ci-token:${{ secrets.GITLAB_CI_TOKEN }}@gitlab.com/mjcarsjens/test_images.git master
          else
            echo "No new snapshots since last run"
          fi
          cd ..
          git submodule update --remote --recursive
          git add .
          git commit -m "build(tests): update submodule ref" && git push || echo "No changes in submodule ref"

      - name: Upload storybook
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path: storybook-static

  deploy-storybook:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download storybook artifact
        uses: actions/download-artifact@v2
        with:
          name: storybook
          path: storybook-static

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: storybook-static

  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: yarn install
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: build library
        run: yarn build

      - name: lerna version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
        run: |
          git push --set-upstream origin HEAD
          yarn release -- --yes

      - name: lerna publish
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_ACCESS_TOKEN}"
          npm config set access public
          npm run publish -- --no-verify-access --yes
          npm config delete "//registry.npmjs.org/:_authToken"
