name: CI/CD Den Haag website branch

on:
  push:
    branches:
      - www.denhaag.nl
  pull_request:
    branches:
      - www.denhaag.nl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js version
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "16.13.x"

      - name: pnpm install
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: run linters
        run: |
          pnpm lint:css
          pnpm lint:package
          pnpm lint:js
          pnpm lint:prettier

      - name: build library
        run: pnpm build:library

      - name: typecheck storybook
        run: pnpm typecheck:storybook

      - name: build storybook
        run: pnpm build:storybook

  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/www.denhaag.nl'

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Set up Node.js version
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "16.13.x"

      - name: pnpm install
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: build library
        run: pnpm build

      - name: lerna version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "Den Haag website"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "Den Haag website"
        run: |
          git push --set-upstream origin HEAD
          pnpm release -- --yes --no-git-tag-version --preid www-denhaag-nl

      - name: lerna publish
        with:
          node-version: "16.13.x"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@gemeente-denhaag"
        env:
          GH_ADMIN_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          npm config set "//npm.pkg.github.com/:_authToken" "${GH_ADMIN_TOKEN}"
          npm config set access public
          npm run publish -- --no-verify-access --yes
          npm config delete "//npm.pkg.github.com/:_authToken"
