name: Build and deploy Storybook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9

      - name: Set up Node.js version
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm ls --recursive

      - name: run linters
        run: |
          pnpm run lint:css
          pnpm run lint:package
          pnpm run lint:js
          pnpm run lint:prettier

      - name: build library
        run: pnpm run build:library

      - name: typecheck
        run: pnpm run typecheck

      - name: build storybook
        run: pnpm run build:storybook

      - name: Upload storybook
        uses: actions/upload-artifact@v4.3.1
        with:
          name: storybook
          path: storybook-static

      - name: Publish to Chromatic
        uses: chromaui/action@v11.3.0
        if: |
          github.event.pull_request.draft == false &&
          github.action != 'dependabot[bot]'
        with:
          autoAcceptChanges: main
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static

  deploy-storybook:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Download storybook artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: storybook
          path: storybook-static

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: storybook-static

  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9

      - name: Set up Node.js version
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm ls --recursive

      - name: build library
        run: pnpm run build

      - name: lerna version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
        run: |
          git push --set-upstream origin HEAD
          pnpm run release

      - name: lerna publish
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_ACCESS_TOKEN}"
          pnpm config set access public
          pnpm run publish
          pnpm config delete "//registry.npmjs.org/:_authToken"
